# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicobytes Website
email: nicolas.molina.monroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software y organizador de comunidades, apasiado por javascript y front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicobytes.com" # the base hostname & protocol for your site
twitter_username: nicobytes
github_username:  nicobytes

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire-me
    url: /hire-me

# Build settings
markdown: kramdown
